name: Deployment

on: push                    ##triggered on a push

jobs:
  installs:
    runs-on: ubuntu-latest    ##runner or os on github
    steps: 
    - name: Get code from local to gh runner
      uses: actions/checkout@v3
    - name: Install nodejs 18
      uses: actions/setup-node@v3
      with:                             ##configs for nodejs 
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Run build
      run: npm run build
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with: 
        name: dist-tuc
        path: dist
    
    # - name: Copy folder content recursively to remote VPS
    #   uses: garygrossgarten/github-action-scp@release
    #   with:
    #       local: dist
    #       remote: /var/www/www.taraka-uc.com/public_html/
    #       host: ${{ secrets.HOST }}
    #       username: ${{ secrets.SSH_USER }}
    #       password: ${{ secrets.PASSWORD }}


# name: First Workflow Name

# on: workflow_dispatch

# jobs:
#   first_job:
#     runs-on: ubuntu-latest

#     steps: 
#     - name: Print greeting
#       run: echo 'Hello, this is the first step in the job first_job'
#     - name: Print Goodbye
#       run: echo 'Done ma bye'
